
@baseUrl = http://localhost:5500

GET {{baseUrl}}/events

GET {{baseUrl}}/events/1

POST {{baseUrl}}/events
Content-Type: application/json

{
    "visitId": 1,
    "eventName": "page_view",
    "pageUrl": "/about",
    "element": "buy-btn"
}

PUT {{baseUrl}}/events/2
Content-Type: application/json

{
    "visitId": 2,
    "eventName": "clicsusk",
    "pageUrl": "/new-page"
}

DELETE {{baseUrl}}/events/1


GET {{baseUrl}}/events/999


POST {{baseUrl}}/events
Content-Type: application/json

{
    "pageUrl": "/test"
}

GET {{baseUrl}}/test